In [1]:
import sklearn,pandas, sklearn.metrics
import numpy as np
from sklearn import datasets

from sklearn.linear_model import LogisticRegressionCV, LogisticRegression
from sklearn.metrics import f1_score,precision_score,recall_score,confusion_matrix
from sklearn.grid_search import GridSearchCV

In [3]:
data = pandas.read_csv('data.train.csv')
data.head()

user_id    item_id  user_action_count  user_lastday_count  \
0   72333767  252905469               1237                  16   
1    7494627  345934335               3465                 104   
2  135670856  305229489               7605                   7   
3    5259651  350868671               2096                   0   
4   32298483   80736633               6516                 107   

   user_buy_count  item_click_count  item_lastday_count  item_buy_count  \
0              27                 2                   0               0   
1              43                 4                   0               0   
2             293                15                   1               1   
3              17                 3                   0               0   
4              20                11                   0               0   

   cat_click_count  cat_buy_count  user_cat_count  user_cat_lastday_count  \
0           307261            833             134                       0   
1           122784            709              11                       0   
2            25230            922            2481                       6   
3                8              0               5                       0   
4           311285            838             952                       0   

   user_item_count  user_item_lastday_count  user_add_car  user_add_star  \
0                2                        0           111             10   
1                3                        0           186             20   
2               10                        0           695            334   
3                3                        0             5             14   
4                2                        0            28              0   

   item_added_car  item_added_start  user_item_lasttime  buy  
0               0                 0          1418342400    0  
1               0                 0          1418367600    0  
2               4                 0          1418702400    1  
3               0                 0          1416312000    0  
4               1                 0          1417492800    0

In [12]:
data.columns

Index([u'user_id', u'item_id', u'user_action_count', u'user_lastday_count', u'user_buy_count', u'item_click_count', u'item_lastday_count', u'item_buy_count', u'cat_click_count', u'cat_buy_count', u'user_cat_count', u'user_cat_lastday_count', u'user_item_count', u'user_item_lastday_count', u'user_add_car', u'user_add_star', u'item_added_car', u'item_added_start', u'user_item_lasttime', u'buy'], dtype='object')

In [20]:
data[[i for i in data.columns if i not in ['user_id','item_id','buy']]]

user_action_count  user_lastday_count  user_buy_count  item_click_count  \
0                  1237                  16              27                 2   
1                  3465                 104              43                 4   
2                  7605                   7             293                15   
3                  2096                   0              17                 3   
4                  6516                 107              20                11   
5                  2000                 142               6                 4   
6                   220                   0               6               470   
7                 11015                   0              67                 4   
8                  3849                 124              36                 4   
9                  4884                   0               6                 2   
10                 1629                  16              10                 1   
11                 5464                  30              35                 1   
12                  196                   0               1                 2   
13                 1372                  85              19                 2   
14                 1481                   0               3               102   
15                 3126                   0               6               103   
16                 2223                 340               5                39   
17                  471                   8               3                 1   
18                  921                  47               2                 9   
19                 4048                  51              40                 2   
20                16092                1210               4                 1   
21                 1253                  66               8                 5   
22                 6463                 191              22                 5   
23                 5738                 321              13                10   
24                 1027                  51               6                 2   
25                 5158                  75             110                 5   
26                 2432                  40              24                 3   
27                 1124                   4              15                 2   
28                 1455                  34               0                 2   
29                 1854                  86               0                 2   
...                 ...                 ...             ...               ...   
4876               1299                   7               3                 1   
4877               1687                  66              29                42   
4878               1963                  34              47                 2   
4879               1743                  62              15                 3   
4880               1956                  15              20                 6   
4881               7487                 190              48                 4   
4882               2380                  76              66                10   
4883               2260                   0               4                41   
4884                237                   0               0                 1   
4885               1616                   4               4                 2   
4886               2924                  91              44                 1   
4887                952                 119               4                 6   
4888                329                   0               5                 1   
4889                 83                   0               2                 1   
4890               2665                  14               4                 1   
4891               1551                  19              47                 5   
4892              16262                 378             127                 2   
4893               4112              

In [3]:
import model5 as model
X = model.GetFeature(data)
Y = data['buy'].as_matrix()

In [4]:
X[:10]

array([[  1.19392247e+00,   2.58776404e+00,   5.89349611e-03],
       [ -1.20397280e+00,  -1.20397280e+00,   8.29383886e-03],
       [ -1.20397280e+00,  -1.20397280e+00,   2.14285714e-02],
       [ -1.20397280e+00,  -1.20397280e+00,   1.75438596e-03],
       [ -1.20397280e+00,  -1.20397280e+00,   1.33116883e-02],
       [ -1.20397280e+00,   8.32909123e-01,   8.91632373e-03],
       [ -1.20397280e+00,  -1.20397280e+00,   3.71900826e-02],
       [ -1.20397280e+00,  -1.20397280e+00,   3.02395906e-03],
       [ -1.20397280e+00,  -1.20397280e+00,   1.27024452e-03],
       [ -1.20397280e+00,  -1.20397280e+00,   6.44641418e-03]])

In [23]:
import model5 as model
reload(model)
clf = model.GetModel()
X,Y = model.GetData()
pred = clf.predict(X)


In [24]:
import summary as smr
reload(smr)
smr.summary(Y, pred)
smr.clf_summary(clf)

F1	P	R
1.39	1.07	1.99

 	F	T
N	555	4578467
P	296	6
best score 0.018542286307
best parms {'C': 0.00046415888336127773, 'class_weight': {0: 1, 1: 100.0}}
-3.50566581963 1.73643435987 -0.199353987403 0.0453562444182


In [10]:
print clf.best_estimator_.coef_[0]

[-0.16534085  1.45092141]


In [35]:
print np.sum(Y)
print np.sum(Y[idx]), np.sum(Y[idx]==0)

302
302 0


In [36]:
clf.grid_scores_

[mean: 0.00260, std: 0.00015, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 100.0}},
 mean: 0.00258, std: 0.00015, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 166.81005372000593}},
 mean: 0.00232, std: 0.00003, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 278.2559402207126}},
 mean: 0.00229, std: 0.00006, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 464.15888336127773}},
 mean: 0.00222, std: 0.00006, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 774.26368268112697}},
 mean: 0.00211, std: 0.00006, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 1291.5496650148841}},
 mean: 0.00202, std: 0.00006, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 2154.4346900318824}},
 mean: 0.00195, std: 0.00007, params: {'C': 9.9999999999999995e-07, 'class_weight': {0: 1, 1: 3593.8136638046258}},
 mean: 0.00185, std: 0.00008, params: {'C': 9.9999999999999995e-07, 'class_weight': {0

In [5]:
data['buy'].value_counts()

0    3539017
1        574
dtype: int64

In [6]:
counts = data['user_item_lastday_count'].value_counts()

In [33]:
np.corrcoef(X[:,0], X[:,1])

array([[ 1.        ,  0.41131407],
       [ 0.41131407,  1.        ]])

In [ ]:
clf.fit(X,Y)

In [43]:
import imp
fp, pathname, description = imp.find_module('model5')
model = imp.load_module('model5', fp, pathname, description)

In [51]:
fp.close()

In [35]:
import pickle
f = open('model1.model','rb')
clf = pickle.load(f)
f.close()

In [13]:
clf.best_params_

{'C': 0.0021544346900318821, 'class_weight': {0: 1, 1: 120}}

In [8]:
clf = LogisticRegression(class_weight={0:1,1:120}, C=0.0021544346900318821)
clf.fit(X,Y)
print clf.intercept_,clf.coef_
print f1_score(Y, clf.predict(X))*100

[-3.33515274] [[ 1.44801788]]
2.02360876897


In [42]:
np.sum(Y)

302

In [29]:
print clf.best_score_,clf.best_params_

0.0209094022246 {'C': 0.00021544346900318845, 'class_weight': {0: 1, 1: 100}}


In [25]:
print np.sum(Y)
predX = clf.predict(X)
print np.sum(predX)
print sklearn.metrics.recall_score(Y, predX), sklearn.metrics.precision_score(Y, predX)
print f1_score(Y, predX)

87
186
0.0574712643678 0.0268817204301
0.03663003663


In [23]:
print np.sum(clf.predict(X_test))

358


In [22]:
print clf.intercept_,clf.coef_

[-4.57766365] [[ 0.65020026  1.34236491]]


In [12]:
y = np.zeros(20)
t = np.linspace(5,100,20)
for i in range(20):
    y[i] = f1_score(Y,X[:,0]>np.log(0.3+t[i]))


In [13]:
%matplotlib inline
pandas.DataFrame(y*100).plot()

In [16]:
print t[5],y[5]
# print X_test
print f1_score(Y_test,(X_test['user_item_count']>t[3]))

30.0 0.0019305019305
0.0


In [5]:
import pickle
with open('model3.model','rb') as f:
    clf = pickle.load(f)
print clf

GridSearchCV(cv=None, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0),
       fit_params={}, iid=True, loss_func=None, n_jobs=16,
       param_grid={'C': array([  1.00000e-06,   5.99484e-06,   3.59381e-05,   2.15443e-04,
         1.29155e-03,   7.74264e-03,   4.64159e-02,   2.78256e-01,
         1.66810e+00,   1.00000e+01]), 'class_weight': [{0: 1, 1: 2}, {0: 1, 1: 10}, {0: 1, 1: 30}, {0: 1, 1: 100}, {0: 1, 1: 300}, {0: 1, 1: 1000}]},
       pre_dispatch='2*n_jobs', refit=True, score_func=None, scoring='f1',
       verbose=0)


In [18]:
print clf.best_score_*100
print clf.best_params_

1.00400405829
{'C': 0.001291549665014884, 'class_weight': {0: 1, 1: 100}}


In [15]:
est = clf.estimator

In [16]:
print clf.score(X,Y)
print clf.predict(X)

0.0194432169686
[0 0 0 ..., 0 0 0]


In [22]:
clf.estimator

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0)

In [34]:
data_test['buy'].value_counts()

0    1179196
1        215
dtype: int64

In [47]:
clf.score(X_test,Y_test)

0.99981770561746497

In [49]:
pred = clf.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
f1_score(Y_test,pred)

0.019891500904159132

In [38]:
np.mean(data_test['buy']==0)

0.99981770561746497

In [23]:
np.mean(pred[:,0]>0.995)

0.99871800415631196

In [65]:
data['buy'].value_counts()

0    3539017
1        574
dtype: int64

In [1]:
data_pred = pandas.read_csv('data.csv')
X_pred=np.log(0.3+data_pred[['user_item_count','user_item_lastday_count']])
Y_pred=data_pred['buy']

NameError: name 'pandas' is not defined

In [7]:
np.array([1,2])+4

array([5, 6])

In [8]:
items = pandas.read_csv('tianchi_mobile_recommend_train_item.csv')


In [14]:
tids=items['item_id']

In [30]:
tids[0]

327414838

In [32]:
'327414838' in list(tids)

False

In [14]:
items = pandas.read_csv('tianchi_mobile_recommend_train_item.csv')

In [17]:
nrow = 10000
start = 0
fr = pandas.read_csv('feature.csv',iterator=True)

In [43]:
'buy' in data.keys()

True

In [25]:
if 0:
    print 111

In [10]:
arr=[1,2,3,4,5,6]
arr[1,2]

TypeError: list indices must be integers, not tuple

In [64]:
fr = pandas.read_csv('data.csv', iterator=True, chunksize=1)

In [72]:
df=fr.get_chunk()
df[:1]

user_id    item_id  user_action_count  user_lastday_count  user_buy_count  \
0  36185714  402065158               4298                  35              13   

   item_click_count  item_lastday_count  item_buy_count  cat_click_count  \
0                 5                   0               0            73028   

   cat_buy_count  user_cat_count  user_cat_lastday_count  user_item_count  \
0           1062             336                       0                3   

   user_item_lastday_count  buy  
0                        0    0

In [51]:
fr.end

AttributeError: 'TextFileReader' object has no attribute 'end'

In [74]:
[1]==1

False

In [76]:
clf.predict([1,1])==0

array([ True], dtype=bool)

模型3

In [3]:
import model0 as model
clf = model.GetModel()

In [4]:
data = pandas.read_csv('data.csv.subset.csv')
data.head()

user_id    item_id  user_item_count  user_item_lastday_count  buy
0   8036273  360815626                3                        3    0
1  27751835  244322130                1                        0    0
2  98692568  371781541                2                        0    0
3  69051488   86334753                1                        0    0
4  65801616  117337750                1                        0    0

In [24]:

X=data[['user_item_count' , 'user_item_lastday_count']].as_matrix()


Y=data['buy'].as_matrix()

In [5]:
data['item_to_cat_rate'] = data['user_item_lastday_count'] / (1 + data['user_cat_lastday_count'])
data['user_item_lastday_count'] = np.log(0.3+data['user_item_lastday_count'])

X=data[['user_item_lastday_count','item_to_cat_rate']].as_matrix()


Y=data['buy'].as_matrix()

In [5]:
X,Y = model.GetData()
clf.score(X,Y)

C:\Python27\lib\site-packages\sklearn\grid_search.py:370: ChangedBehaviorWarning: The long-standing behavior to use the estimator's score function in GridSearchCV.score has changed. The scoring parameter is now used.
  ChangedBehaviorWarning)


0.018018018018018018

In [27]:
np.sum(clf.predict(X))

1263

In [28]:
np.corrcoef(X[:,0],X[:,1])

array([[ 1.        ,  0.07609058],
       [ 0.07609058,  1.        ]])

In [29]:
clf.best_params_

{'C': 0.0001, 'class_weight': {0: 1, 1: 150}}

In [2]:
import model4 as model

In [3]:
data=pandas.read_csv('feature_total.csv.subset.csv')

In [4]:
data.head()

user_id    item_id  user_action_count  user_buy_count  \
0   8036273  360815626               9622              57   
1  27751835  244322130                843               7   
2  98692568  371781541                567              12   
3  69051488   86334753               4191               7   
4  65801616  117337750               3125              41   

   user_cat_lastday_count  user_item_count  user_item_lastday_count  
0                       2                3                        0  
1                       0                1                        0  
2                       0                2                        0  
3                       0                1                        0  
4                       0                1                        0

In [5]:
X = model.GetFeature(data)


In [6]:
X

array([[-1.2039728 ,  0.83290912,  0.00592331],
       [-1.2039728 , -1.2039728 ,  0.00829384],
       [-1.2039728 , -1.2039728 ,  0.02112676],
       ..., 
       [-1.2039728 , -1.2039728 ,  0.00498168],
       [-1.2039728 , -1.2039728 ,  0.00378469],
       [-1.2039728 , -1.2039728 ,  0.02153846]])

In [7]:
clf = model.GetModel()

In [8]:
pred = clf.predict(X)

In [9]:
pandas.value_counts(pred)

0    4718243
1        759
dtype: int64

In [10]:
clf.best_score_

0.021700012211406602

In [17]:
X=0
data=0


In [56]:
import time

In [57]:
time.ctime()

'Thu Apr 02 13:39:12 2015'

In [62]:
t=time.strptime('2014-12-18 10','%Y-%m-%d %H')

In [66]:
time.mktime(t)

1418868000.0

In [72]:
pandas.value_counts((data['buy']==1) | (np.random.rand(len(data))<0.01))

False    4533311
True       46013
dtype: int64

In [73]:
idx=(data['buy']==1) | (np.random.rand(len(data))<0.01)

In [74]:
data[idx]

user_id    item_id  user_action_count  user_buy_count  \
6         48034560  302154307                241               9   
18       119510685  379792585               2063               4   
162       44548696  281779470                774               0   
168      127845416   65938545               3476              21   
389       55197721   37566103               1881               3   
402       22921488  228231654               3300              44   
965       33638786  252411515               3751              43   
1021      81525436  387403013               2869              22   
1039      85528205  120747601               9835             143   
1136      14739519  251987605                323               4   
1204      84502169  165064665               2226              18   
1664      42659811  246260362               6463              22   
1682      79868555  167031724               1721              10   
1778      68627095  283951390               1524              11   
2218       6338284   23302641               1888               0   
2279      92684627  294067666                204               8   
2539     129862703  231077079               1610              83   
2692      43113553  154746543               4593             102   
2726      91388134   55941419               3422              12   
2741       3503734  151289042              11728              95   
2770     135670856  305229489               7605             293   
2933      41017565  369970723               3185               1   
2944      63582274  389964470                443               6   
2945      68943297  223065449               1254              23   
3051      51450804  290112559               1981              19   
3085      98438834  246066848               2265              25   
3122     106840813  143249084               1487              37   
3151     111849931  144690794              10061              52   
3256     134622261   89233341               1681               6   
3442     133042920   21587635                762               3   
...            ...        ...                ...             ...   
4576836  122695388  297987267                898              10   
4576942  100699621  204824487               6456              22   
4576944   12608436   15335020               3436              35   
4577029   35194603  357213564               1362              19   
4577032  103969132  162817707              12236              60   
4577116   95734270  173115873                767               5   
4577141   28242823  297220121               1885              33   
4577247   33486899  141487875               1221              10   
4577300  127189529  257902972                624               2   
4577467   98080912  332677968               3325              26   
4577485   60756558  363359676               1961               5   
4577529   77381364  219075820               1222              18   
4577719   89362349  192396499               5801              15   
4577801   32123143  185765523              19006              23   
4577926   74470519  135470249               2139              40   
4577975   46495539  134871111               1604              13   
4578203   28490094  317723255               4992              25   
4578213   12779464  115420533               3144               6   
4578371   18538455   14875502               1233              32   
4578426  123783088  210415092               3800              42   
4578440  125470535  131890322                875               1   
4578454  101703391  323450897                414               5   
4578727   46380691   53616768                627               5   
4578778   47606728  316711353                167               0   
4578786  109474226  301564631               2019               6   
4578877   58074259  240273185               1822              22   
4578937    4273621   10089709               1923              10   

In [23]:
idx = data['buy']==1

In [30]:
np.sum((~idx) * np.random.rand(len(idx)))

2319.0124061381648

In [63]:
import model7 as model
reload(model)

<module 'model7' from 'model7.py'>

In [64]:
clf = model.GetModel()

In [65]:
TP,TN,FP,FN = model.TestModel()

===== for test =====
 	F	T
N	4575121	3901
P	257	45
F1	P	R
2.12	1.14	14.90


In [62]:
P = float(TP)/(TP+TN)
0.

0.0

In [37]:
data = reader.get_chunk()

In [54]:
X_test = model.GetFeature(data)
Y_test = data['buy'].as_matrix()
pred = clf.predict(X_test)

TP = TP + np.sum(Y_test * pred)
TN = TN + np.sum((1-Y_test) * pred)
FP = FP + np.sum(Y_test * (1- pred))
FN = FN + np.sum((1- Y_test) * (1- pred))

In [55]:
print TP,TN,FP,FN

15 910 -4 299079


In [53]:
pandas.value_counts((1-pred) )

1    99075
0      925
dtype: int64